---
- hosts: all
  sudo: yes

  tasks:

    - name: Add dotdeb key
      apt_key: url=http://www.dotdeb.org/dotdeb.gpg state=present
    - name: Setup APT sources
      template: src=sources.list dest=/etc/apt/sources.list

    - name: Update APT
      apt: update_cache=yes

    - name: Essentials
      apt: name={{ item }} state=latest
      with_items:
      - wget
      - htop
      - screen
      - nmap

    - name: Install Git
      apt: name=git state=latest

    - name: Install Nginx
      apt: name=nginx state=latest

    - name: Copy Nginx default configuration
      template: src=default.conf.j2 dest=/etc/nginx/sites-enabled/default
      notify: restart nginx

    - name: Install Mysql
      apt: name=mysql-server state=latest

    - name: Install Python mysqldb
      apt: name=python-mysqldb state=latest

    - name: Install PHP
      apt: name=php5-fpm state=latest
      notify: restart nginx

    - name: Restart Nginx
      service: name=nginx state=restarted


  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart mysql
      service: name=mysql state=restarted